import Layout from './../components/Layout';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { getCookie } from 'cookies-next';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import ReactLoading from 'react-loading';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>Please Login</main>
      </Layout>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  // if (!token) {
  //   return {
  //     redirect: {
  //       destination: '/auth/login',
  //     },
  //     props: {},
  //   };
  // }
  return {
    props: {},
  };
};

export default Home;
